# Generated by Django 3.2.5 on 2021-07-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URL',
        ),
    ]
